Piece-wise linear function
Amioplk/Apartments pull request #14
Opened 2019-06-03 21:14 UTC by LaurenceTsizaza

Nous avons créé la branche piecewiselinear à partir de la branche update, or cette branche fait déjà l'objet d'un autre pull request. Le seul fichier à prendre en compte ici est le fichier PieceWiseLinearValueFunction.java.

2019-06-04 18:47 UTC, oliviercailloux requested changes

2019-06-04 18:47 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/PieceWiseLinearValueFunction.java
> +		map = new ConcurrentSkipListMap<Double, Double>(parameters);
Pourquoi ce choix de classe ? Utiliser Guava ImmutableSortedMap.

2019-06-04 18:47 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/PieceWiseLinearValueFunction.java
> +	private boolean CheckValues() {
- Conventions de nommage.
- Nom malheureux. Il faut décrire la condition testée : isWeaklyMonotonous par exemple (si c’est bien ce que vous voulez vérifier).
- Appeler une méthode existante qui vérifie que les valeurs sont déjà triées serait préférable (REUSE).

2019-06-04 18:47 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/PieceWiseLinearValueFunction.java
> +	 * to be positive.
… to be non-negative. (plus précis)

2019-06-04 18:47 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/PieceWiseLinearValueFunction.java
> +			throw new IllegalArgumentException("The value associated to the grade 0 or 1 is missing.");
Ne pas logger et jeter, le récepteur de l’exception risque fort de vouloir logger aussi

2019-06-04 18:47 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/PieceWiseLinearValueFunction.java
> +		Object[] keys = map.keySet().toArray();
Enlevez-moi très vite ce code qui non seulement utilise un vecteur ancien style mais en plus oblige au cast en perdant l’information de typage. Utiliser un peeking iterator de Guava par exemple.

2019-06-07 18:55 UTC, oliviercailloux requested changes
FORMAT. FOCUS.

2019-06-07 18:55 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/PieceWiseLinearValueFunction.java
> +	private SortedMap<Double, Double> map; // K : value, V : grade
javadoc style comments SVP

2019-06-07 18:55 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/PieceWiseLinearValueFunction.java
> +	 * If the collection of keys is sorted, then the collection of grades also has to be sorted.
Corriger la ponctuation. Exprimez-vous plus clairement, « If the collection of keys is sorted, then the collection of grades also has to be sorted. » n’est pas vraiment la condition que vous demandez.

2019-06-07 18:55 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/PieceWiseLinearValueFunction.java
> +		return Comparators.isInOrder(values, comparator);
Pourquoi copier dans une liste ? Tout ceci peut s’écrire en une seule ligne. Dès lors, la méthode n’est plus justifiée.

2019-06-07 18:55 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/PieceWiseLinearValueFunction.java
> +	public double getSubjectiveValue(Double objectiveData) throws IllegalArgumentException {
BP null (partout)

2019-06-07 18:55 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/PieceWiseLinearValueFunction.java
> +		}
Il serait conceptuellement plus élégant et plus clair, et équivalent, d’utiliser la map triée et de vérifier que la première valeur égale zéro et la dernière égale un.

2019-06-07 18:55 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/PieceWiseLinearValueFunction.java
> +		if(map.isEmpty() || map.size() < 2) {
La map ne peut avoir une taille inférieure à deux ici, vu votre constructeur, sauf erreur de ma part.
Privilégier donc `Verify` de Guava.

2019-06-07 18:55 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/y2018/apartments/readApartments/ReadApartmentsXMLFormatTest.java
> +	void readApartmentTest() throws IOException, IllegalArgumentException, IllegalAccessException{
BP Exceptions

2019-06-07 18:55 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/PieceWiseLinearValueFunction.java
> +		Double maxKey = iterator.next();
D’après moi c’est plutôt minKey. Je ne comprends pas votre algo, en l’état. Mais quoi qu’il en soit, vous devriez utiliser une NavigableMap et trouver directement les clés qui vous intéressent.

2019-06-17 16:47 UTC, LaurenceTsizaza commented on src/test/java/io/github/oliviercailloux/y2018/apartments/readApartments/ReadApartmentsXMLFormatTest.java
> +	void readApartmentTest() throws IOException, IllegalArgumentException, IllegalAccessException{
Bonjour,
Ce fichier n'est pas à prendre en compte. Il est modifié dans une autre branche.

2019-06-17 17:26 UTC, oliviercailloux requested changes
FORMAT

2019-06-17 17:26 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/PieceWiseLinearValueFunction.java
> +	private ImmutableSortedMap<Double, Double> map;
`map`, pour une `Map`, n’est pas un nom très descriptif. `utilities`, par exemple, est plus informatif.

2019-06-17 17:26 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/PieceWiseLinearValueFunction.java
> +	public PieceWiseLinearValueFunction(Map<Double, Double> parameters) {
Nommer un argument `parameters` n’est pas plus informatif. `utilities` convient également ici.

2019-06-19 15:51 UTC, oliviercailloux requested changes
Ça m’a l’air bon pour cette implémentation. Manquent des tests unitaires nécessaires avant approbation. Pour la prochaine review, merci de mettre vos modifications à part dans une branche (FOCUS).

2019-06-20 12:03 UTC, LaurenceTsizaza commented
Bonjour,
Les tests sont déjà présents sur une autre branche qui donnera bientôt suite à un pull request.

2019-06-20 14:22 UTC, oliviercailloux requested changes
FOCUS

2019-06-21 07:29 UTC, closed without merging