Readme livraison2
Amioplk/Apartments pull request #18
Opened 2019-06-05 09:30 UTC by Amioplk

This is the guidlines we followed during the 2nd delivery

2019-06-05 12:38 UTC, Amioplk commented
@oliviercailloux new PR concerning 2nd delivery -> replace #9

2019-06-06 17:05 UTC, oliviercailloux approved these changes

2019-06-06 17:05 UTC, oliviercailloux commented on README.adoc
> +** Créer un fichier XML à partir de ces informations
Non, il faut créer un appartement en mémoire à partir de ces informations. Ensuite, on fait ce qu’on veut avec cet appartement en mémoire (par exemple, l’enregistrer dans un format XML).

2019-06-06 17:05 UTC, oliviercailloux commented on README.adoc
> +* L’utilisateur peut indiquer en voyant la liste d’annonces qu’il préfère une annonce à une autre alors qu’elle est classé sous la deuxième. Le système lui permet alors de corriger son utilité pour q
Ces deux tâches de spécification indirecte d’utilité me semblent difficiles à accomplir. Je ne suis pas sûr de comprendre ce que vous avez en tête. En tous cas, je vous suggère plutôt qqch. de plus simple. Par exemple, l’utilisateur devrait pouvoir spécifier son utilité directement, en définissant ses fcts de valeur partielles (en supposant par exemple que la fct est linéaire, il suffit de préciser l’intervalle). Commencez simple et complexifiez ensuite !

2019-06-06 17:05 UTC, oliviercailloux commented on README.adoc
> +CAUTION: Ces dernières fonctionnalités ne peuvent fonctionner que si on a un GUI pour indiquer la liste des annonces qui sont suceptibles de plaire à l'utilisateur
Ce n’est pas tout-à-fait vrai. En supposant que l’utilisateur final a spécifié ce qui lui plait, vous pouvez déjà implémenter la logique de détermination des utilités sans avoir de GUI.

2019-06-06 17:06 UTC, oliviercailloux requested changes
Je voulais dire : changes requested

2019-06-06 17:15 UTC, Amioplk commented
@oliviercailloux 

Bonjour monsieur,

Ce PR vaut pour la 2e itération.
Vos remarques concernent la troisième itération et la suite et non le plan de la 2nd itération.
Devons-nous déjà changer le propos du readme par rapport à ces remarques dès maintenant dans ce PR ou ne serait-ce pas plus clair que l'actuelle SM/PO de l'itération 3 le fasse ?
Comme nous devons vous envoyer le readme de la 3e livraison ASAP, ne devrions-nous pas accepter ce readme ?

Cordialement.

2019-06-07 09:18 UTC, oliviercailloux approved these changes
Effectivement mes remarques ne peuvent pas être prises en compte sur la livraison2, mais bien sur la 3.

2019-06-07 09:23 UTC, merged