GUI Functionnality
Amioplk/Apartments pull request #21
Opened 2019-06-05 14:02 UTC by Aichaaa

Start : Show the user a single apartment from an XML file
During : We figured out that the ReadApartmentXMLFormat does not work as it should

-> finish after the 2nd delivery

2019-06-05 14:02 UTC, Aichaaa commented
Replaces PR #

2019-06-07 12:30 UTC, oliviercailloux requested changes
ECL
Décomposer en méthodes, …

2019-06-07 12:30 UTC, oliviercailloux commented on pom.xml
> +					<version>3.106.3</version>
Utiliser SVP la dernière version, tant que vous y êtes.

2019-06-07 12:30 UTC, oliviercailloux commented on pom.xml
> +	 </dependency>   -->
Ne pas utiliser junit 4, plutôt junit 5. Enlever le code commenté : votre dépôt est là pour revenir en arrière si nécessaire (BP style commented code).

2019-06-07 12:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/PrintApartementGUI.java
> +	public Apartment appar;
`private Apartment apar`

2019-06-07 12:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/PrintApartementGUI.java
> +	protected static Shell shell = new Shell(display);
Should be instance fields for coherency and object-oriented behavior.

2019-06-21 06:59 UTC, closed without merging