Iteration3 readme
Amioplk/Apartments pull request #22
Opened 2019-06-10 20:45 UTC by LaurenceTsizaza

Voici les tâches pour la troisième itération.

2019-06-11 12:03 UTC, oliviercailloux requested changes

2019-06-11 12:03 UTC, oliviercailloux commented on README.adoc
> +1^er^ Duo : Développer un GUI qui affiche d'une liste d'appartements à l'utilisateur + tri des appartement en fonction de l'utilité de l'utilisateur
Il vous faut d’abord une manière d’obtenir une instance représentant l’utilité de l’utilisateur. Par exemple, vous pourriez la générer aléatoirement, ou générer une valeur constante (c’est le plus facile), ou la lire depuis un fichier. En tous cas, il vous faut une (ou plusieurs) tâche pour ça. À moins que ce soit déjà fait, c’est possible que je ne l’aie plus en tête.

2019-06-11 12:03 UTC, oliviercailloux commented on README.adoc
> +Une méthode permettant à l'utilisateur de définir son utilité existe déjà.
C’est là où je doute. Quelle classe fait ça ? Il faut en outre une manière automatique de générer des utilités, pas seulement via un GUI.

2019-06-12 18:58 UTC, LaurenceTsizaza commented on README.adoc
> +Une méthode permettant à l'utilisateur de définir son utilité existe déjà.
Bonsoir,
La classe ApartmentValueFunction est doté d'un constructeur initialisant les méthodes de calcul du score de l'appartement (PartialValueFunction) avec des constantes par défaut de l'utilité de l'utilisateur.

2019-06-13 16:35 UTC, oliviercailloux approved these changes
Ok pour cette tâche qui s’appuiera, si j’ai bien compris, sur une fct d’utilité unique. Ajoutez une tâche pour génération aléatoire d’utilités (éventuellement à reporter en itération 4).

2019-06-13 19:17 UTC, merged