Display a list of sorted apartments and layout details
Amioplk/Apartments pull request #23
Opened 2019-06-20 17:25 UTC by Aichaaa

Pour cette itération, nous avons créé une classe  « LayoutApartmentGUI ». Cette classe contient une méthode « displayAppart » qui affiche la liste des appartements générés aléatoirement à l'aide la fonction generateRandomXML ()  . A l’aide de GridLayout et GridData nous avons ajouté des labels dans le shell.
Cette liste est triée selon l’utilité de l’utilisateur à l’aide de la méthode ApartmentValueFunction(). Quand l’utilisateur sélectionne un appartement dans la liste, on affiche à l’aide de. getSelectionIndices() des détails sur l’appartement sélectionné.

2019-06-20 18:55 UTC, oliviercailloux requested changes
Cette PR dépend d’une autre (PR #19) qui a été fusionnée erronément. J’attends la résolution de ce problème avant de commenter plus avant.

2019-06-20 18:55 UTC, oliviercailloux commented on pom.xml
>  <?xml version="1.0" encoding="UTF-8"?>
Résoudre problème avec pom.

2019-06-20 18:55 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/ApartmentValueFunction.java
> +		//LOGGER.info("the floor area subjective value has been set to "+ floorAreaSubjectiveValue);
L’utilisation d’un logger a précisément pour objectif de ne pas devoir commenter et dé-commenter son usage. Vous pouvez modifier le degré d’importance, par contre.

2019-06-20 19:28 UTC, Aichaaa commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/ApartmentValueFunction.java
> +		//LOGGER.info("the floor area subjective value has been set to "+ floorAreaSubjectiveValue);
Oui on avait mis des commentaires pour réduire l'affichage pendant les tests de notre fonction trie. Nous allons les supprimer.

2019-06-20 19:35 UTC, Aichaaa commented on pom.xml
>  <?xml version="1.0" encoding="UTF-8"?>
On a pas de problème avec le pom. Chez nous ça marche bien. D'ailleurs pour cette itération on ne s'est pas intéréssé à ce fichier à part pour régler des conflits .On avait décidé d'améliorer le pom à la dernière itération.

2019-06-20 19:44 UTC, Aichaaa reviewed
commentaires enlevés

2019-06-26 14:34 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/ApartmentValueFunction.java
> +		//LOGGER.info("the floor area subjective value has been set to "+ floorAreaSubjectiveValue);
Précisément, l’objectif est de ne pas devoir commenter puis (risquer d’oublier de) retirer les commentaires. Il aurait mieux valu modifier le degré d’importance, et le laisser comme ça.

2019-06-26 14:35 UTC, oliviercailloux commented on pom.xml
>  <?xml version="1.0" encoding="UTF-8"?>
Voyez dans le diff du pom sur GitHub le problème du pom.

2019-06-26 14:45 UTC, oliviercailloux requested changes
- Pas tout en statique, ces méthodes doivent être des méthodes d’instance, sauf exception justifiée.
- Votre instance doit avoir comme champ la liste d’appartements qu’elle est censée montrer, cela clarifiera les choses.
- Accepter en paramètre des types aussi généraux que possibles.

2019-06-26 14:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/toxmlproperties/XMLProperties.java
> +}
Enlevez cette différence qui n’a rien à y faire en restaurant l’original.

2019-06-26 14:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/LayoutApartmentGUI.java
> +			Apartment a = XMLProperties.generateRandomXML(); // lately we will use generateRandom
Oui, veuillez utiliser la génération correcte (qui n’est pas liée à XMLProperties), qui est maintenant fusionnée, sauf erreur de ma part.

2019-06-26 14:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/LayoutApartmentGUI.java
> +				(Apartment c, Apartment d) -> (int) ((avf.getSubjectiveValue(c) - avf.getSubjectiveValue(d)) * 100000));
Pourquoi cette conversion en entier ? Utilisez SVP une référence de méthode en guise de comparateur pour plus de lisibilité, car ce code est difficile à comprendre.

2019-06-26 14:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/LayoutApartmentGUI.java
> +		GridLayout gridLayout = new GridLayout();
Extraire toute la partie initialisation des divers objets graphiques dans une méthode appelée par exemple `init()` clarifierait les choses.

2019-06-26 14:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/LayoutApartmentGUI.java
> +		list.addSelectionListener(new SelectionAdapter() {
Utiliser une référence de méthode SVP pour éviter cette imbrication peu claire, lire la javadoc des classes que vous utilisez pour vous aider.

2019-06-29 09:44 UTC, Amioplk commented on src/main/java/io/github/oliviercailloux/y2018/apartments/toxmlproperties/XMLProperties.java
> +}
Mauvaise manipulaition, c'est à jour avec master de toute façon, ne pas y faire attention SVP

2019-06-29 12:47 UTC, oliviercailloux requested changes
Assurez-vous que le check Travis apparaisse SVP (cf. PR #29).

2019-06-30 08:06 UTC, oliviercailloux requested changes
POM toujours (cf. commentaire et réponse à votre réponse précédents).

2019-06-30 08:06 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/LayoutApartmentGUI.java
> +		listShell.addSelectionListener(new SelectionAdapter() {
Utiliser une référence de méthode pour éviter cette imbrication peu claire.

2019-06-30 10:18 UTC, oliviercailloux approved these changes
Tant pis pour le commentaires précédent sur les références de méthodes non pris en compte, cette PR peut être fusionnée moyennant correction mineure ci-dessous.

2019-06-30 10:18 UTC, oliviercailloux commented on pom.xml
> +			<version>1.7.5</version>
Pourquoi 5 au lieu de 26 ?

2019-06-30 10:18 UTC, oliviercailloux commented on pom.xml
> +			<type>jar</type>
Sous-entendu, à retirer.

2019-06-30 14:26 UTC, merged