Random generate correction
Amioplk/Apartments pull request #24
Opened 2019-06-20 20:01 UTC by Amioplk

Voici le PR donnant suite au malencontreux merge du PR de generateRandom2.
Ce merge est en effet une erreur résultant d'une mauvaise manip du membre du groupe.

Comme la correction aurait nécessité une branche pour revenir à l'état d'avant merge, nous avons fait le choix de finaliser la prise en compte de vos remarques sur l'ancien PR.

2019-06-20 20:07 UTC, Amioplk commented
Tâches précises réalisées ici :
- Résolution des problèmes avec le dossier où se trouvent les appartements générés et MAJ .gitignore
- Se débarrasser des warnings
- Formater
- Se débarrasser des références au mot XML car il n'est plus question de créer des .xml ainsi que des exceptions qu'il n'a plus lieu de lancer
- Résolution des problèmes de style JavaDoc
- Utilisation des ImmutableList
- Création d'un builder pour appartements

2019-06-21 06:43 UTC, oliviercailloux commented
Suite PR #19.

2019-06-21 07:38 UTC, oliviercailloux requested changes

2019-06-21 07:38 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/toxmlproperties/XMLProperties.java
> +		xmlFile.close();
Si vous n’avez pas ouvert le stream, ce n’est pas à vous de le fermer.

2019-06-21 07:38 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/toxmlproperties/XMLProperties.java
> +		}
Nous avions déjà parlé de cette approche, qui ne me convainct pas. Le fichier ne doit pas changer si on renomme des champs.

2019-06-21 07:38 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/toxmlproperties/XMLProperties.java
> +		builder.setTitle(titles.get(n));
Il me semble que le titre et l’adresse devraient être tirés aléatoirement séparément, pour plus de diversité dans ce bas monde.

2019-06-21 07:57 UTC, Amioplk commented on src/main/java/io/github/oliviercailloux/y2018/apartments/toxmlproperties/XMLProperties.java
> +		}
La méthode toXML est en vert car nous avons formaté le code. Néanmoins ce code date du groupe de l'année dernière. Aussi, nous ne comprenons pas vraiment le problème. Vous voudriez qu'on modifie cette méthode pour ne pas utiliser Field ?

De plus, est-ce que cela peut faire l'objet d'une petite tâche à la 4e itération ? Etant donné que ce n'était pas le but de ce PR.

2019-06-21 08:02 UTC, Amioplk commented on src/main/java/io/github/oliviercailloux/y2018/apartments/toxmlproperties/XMLProperties.java
> +		}
Reminder : Vous nous avez répondu de vive voix que oui.

2019-06-21 08:07 UTC, Amioplk commented on src/main/java/io/github/oliviercailloux/y2018/apartments/toxmlproperties/XMLProperties.java
> +		xmlFile.close();
C'est résolu

2019-06-21 08:08 UTC, Amioplk commented on src/main/java/io/github/oliviercailloux/y2018/apartments/toxmlproperties/XMLProperties.java
> +		builder.setTitle(titles.get(n));
Dans le PR #19 mergé inopinemment, vous nous disiez :

"Par ailleurs, ce code peut être rendu plus élégant. Le titre devrait être tiré au hasard parmi un ensemble de possibilités. L’adresse idéalement devrait être choisie au hasard mais ceci pourrait être difficile à implémenter et ne vaut pas vraiment la peine. Vous pouvez utiliser la même approche que pour le titre : un petit nombre d’adresses possibles inscrites en dur dans un ensemble, et un choix aléatoire."

Il nous semble que c'est la cas ? Peut-être avons-nous mal compris.

2019-06-21 09:07 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/toxmlproperties/XMLProperties.java
> +		builder.setTitle(titles.get(n));
Pour le moment, un appartement ayant le titre T1 a nécessairement l’adresse A1. Il faudrait mélanger, de façon à ce que l’adresse ne soit pas liée au titre, donc à permettre de générer des appartements ayant des titres et adresses sélectionnés indépendamment.

2019-06-22 06:51 UTC, oliviercailloux approved these changes

2019-06-24 21:34 UTC, merged