Load images apartment
Amioplk/Apartments pull request #28
Opened 2019-06-20 21:43 UTC by aitalibraham

Dans cette itération 3, on s'est intéressé à l'ajout des images dans le projet, et faire les corrections nécessaires pour la lecture et l'affichage d'un appartment. 

- Dans un premier lieu, on a ajouté les attributs nécessaires dans les classes Apartment et dans le fichier XML. (un attribut ImagesFolder, répertoire source où on peut sauver les images d'un seul appartment, et un attribut images, liste des paths images dans ce répertoire.) 
- Dans un second temps, on a implémenté les méthodes de lecture d'images à partir du XML, et les méthodes de parcours et extraction d'images à partir du répertoire.
- La troisième étape était l'amélioration de la classe PrintApartmentGui pour pouvoir afficher des images liés à un apartment, et de pouvoir naviguer entre elles à l'aide d'un bouton. Cette amélioration a touché aussi le design de ce GUI. 
- Finalement, pour pouvoir tester tout cela, on a effectué des tests unitaires, pour voir si les paths sont bien gérés, et que les méthodes permettent de bien récupérer les éléments du répertoire imageFolder.

Difficultés rencotrées : 

- Gestion des class paths compliqués, on a dû changer plusieurs fois les méthodes de chargement des images. 
- Manipulation d'un nouvelle bibliothèque graphique, nécessite un temps pour se former et pouvoir faire des jolis designs.

2019-06-21 09:39 UTC, oliviercailloux requested changes
FOCUS : les changements à ReadApartmentsXMLFormat par exemple ou au pom.xml ne sont pas liés à cette tâche, j’imagine.

2019-06-21 12:16 UTC, aitalibraham commented
Les changements liés au pom ne sont pas concernés, on a juste fusionné avec la branche AddImagesToApartment pour ajouter les dépendances swt et utiliser cette bibliothèque. 
Le seul changement sur ReadApartmentXML concenrne l'ajout des attributs d'iimages (lecture depuis l'XML).

2019-06-22 06:54 UTC, oliviercailloux requested changes
FOCUS quand-même

2019-06-27 20:43 UTC, aitalibraham commented
Branche mise à jour, on a gardé uniquement les changements effectués.

2019-06-29 16:21 UTC, oliviercailloux requested changes
- FORMAT
- À quoi servent vos images placées dans votre class path ?

2019-06-29 16:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/apartment/Apartment.java
> +	 * @param imagesfolder contains the folder images ressources related to the apartment
Enlever `@param imagesfolder` : on sait très bien ce que vous documentez ici.

2019-06-29 16:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/apartment/Apartment.java
> +	private String imagesFloder;
- Folder, plutôt.
- Ce doit être un `Path`, plus adapté que `String`.

2019-06-29 16:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/apartment/Apartment.java
>  	 *          created without a floor area.
Corriger la doc.

2019-06-29 16:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/apartment/Apartment.java
> +	private ArrayList<String> images;
GNRL

2019-06-29 16:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/apartment/Apartment.java
> +	public void addImages(String image) {
Apartment, sauf erreur de ma part, a été conçu comme immuable. Il faut respecter ce choix !

2019-06-29 16:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/CreateApartmentGUI.java
> +    */
BP style

2019-06-29 16:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/PrintApartementGUI.java
> +	 */
Mais que fait ce commentaire ici ?

2019-06-29 16:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/apartment/Apartment.java
>  	public boolean equals(Object obj) {
Il faut ajuster `equals` (et donc `hashCode`) si vous ajoutez des attributs à un appartement.

2019-06-29 16:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/PrintApartementGUI.java
> +	   button1.addSelectionListener(new SelectionAdapter() {
Utiliser plutôt des références de méthodes pour éviter les imprications.

2019-06-29 16:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/PrintApartementGUI.java
> +	    	e.printStackTrace();
EXC

2019-06-29 16:21 UTC, oliviercailloux commented on src/test/resources/io/github/oliviercailloux/y2018/apartments/readApartments/xmlfileTest.xml
> +	<entry key="Images">/home/yanis/Documents/Apartments/src/test/resources/io/github/oliviercailloux/y2018/apartments/readApartments/Images_A</entry>
Votre class path ne contient pas des répertoires au sens normal de fichiers sur le disque, et ce chemin ne correspond à rien sur un autre ordinateur que le vôtre. Utiliser un chemin relatif.

2019-06-29 16:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/PrintApartementGUI.java
> +	public PrintApartementGUI() throws IOException, IllegalArgumentException, IllegalAccessException {
Pas clair, je m’attends d’après ce nom à une impression sur une imprimante. Vous voulez dire `ShowApartmentGUI`, peut-être ?

2019-06-29 19:44 UTC, aitalibraham commented on src/main/java/io/github/oliviercailloux/y2018/apartments/apartment/Apartment.java
> +	private String imagesFloder;
On a mis String pour simplifier la lecture à partir du XML.

2019-06-29 20:06 UTC, aitalibraham reviewed
Revue de l'ensemble des commentaires

2019-06-29 20:08 UTC, aitalibraham commented on src/main/java/io/github/oliviercailloux/y2018/apartments/apartment/Apartment.java
> +	private ArrayList<String> images;
Problème corrigé,

2019-06-30 16:34 UTC, oliviercailloux requested changes
- S’appelle toujours `PrintApartment`
- Je ne vois pas votre réponse à ma question : À quoi servent vos images dans votre class path ?
- SPEC, toujours
- Toujours problèmes @param
- Toujours floder au lieu de folder
- Apartment toujours pas immuable
- GNRL, toujours
- Path toujours pas utilisé, mais ok pour abandonner cet aspect comme demandé si vous ne savez pas comment l’utiliser.

2019-06-30 16:34 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/PrintApartementGUI.java
> +	public static void main(String args[]) throws IllegalArgumentException, IllegalAccessException, IOException {
BP exc

2019-06-30 16:34 UTC, oliviercailloux commented on src/main/resources/io/github/oliviercailloux/y2018/apartments/gui/apartTest.xml
>  <?xml version="1.0" encoding="UTF-8" standalone="no"?>
On attend plutôt d’un fichier nommé …Test qu’il soit dans la partie test, pourquoi ce déplacement dans main ?

2019-06-30 17:51 UTC, aitalibraham commented
ImagesFolder est le nom du repertoire dans ressources qui contiendra les images de l'appartement. 
J'ai mis à jour les classes que j'ai créees dans cette branche, 
Pour l'appartment, je vois pas ce que vous voulez dire par Immuable, car la liste contient des images, avec possiblité d'ajouter ou de supprimer. (On pourra supprimer la méthode AddImages, mais comme la construction se fait dans la class showApartmentGUI, ça peut-être problématique) 
Merci pour toute vos remarques,  

Cordialement,

2019-06-30 18:43 UTC, oliviercailloux requested changes
Retirer JUnit 4 de vos dépendances dans votre POM, et adapter vos tests, qui pour le moment ne sont pas exécutés par Travis (sinon ils ne passeraient pas tous).

(Pour le reste, il est maintenant trop tard, et la PR est de qualité acceptable sans ces modifications.)

2019-06-30 20:20 UTC, aitalibraham commented
Bonsoir, 

J'ai mis à jour les test à JUNIT 5. 

Merci, 
Cordialement,

2019-06-30 21:46 UTC, oliviercailloux requested changes
Travis

2019-06-30 22:20 UTC, aitalibraham commented
Quand je fais mvn test,cela ne donne aucune erreur, l'utlisation de junit 5 fait echouer Travis, je ne comprends pas pourquoi. (sachant que les tests passent bien en local)

Vu le temps que j'ai passé dessus, je préfere l'abandonner.

Merci, bonne soirée, 
Cordialement,

2019-06-30 23:00 UTC, aitalibraham commented
Malgré que j'ai séparé les sources pour les tests, 
Travis echoue.

2021-04-16 14:39 UTC, closed without merging