ApartmentValueFunction aléatoire
Amioplk/Apartments pull request #31
Opened 2019-06-21 12:21 UTC by Amioplk

Suite à un focus, voici la tâche de génération d'une instance aléatoire de ApartmentValueFunction.

2019-06-22 07:52 UTC, oliviercailloux requested changes

2019-06-22 07:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/utils/RandomRange.java
> +		Random random = new Random();
Commencer par vérifier que min < à max, ou ≤ selon vos choix (à documenter).

2019-06-22 07:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/utils/RandomRange.java
> +		int var = random.nextInt(max) + min;
Ceci ne tire pas un nombre entre min et max

2019-06-22 07:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/ApartmentValueFunction.java
> +		apartValueFunction.setNbBedroomsValueFunction(new DiscreteValueFunction<Double>(nbBedroomsEndBoundMap));
C’est bien alambiqué ! Vous auriez pu utiliser une LinearValueFunction, ça revient au même (si j’ai bien compris ce que vous voulez faire). (Changement facultatif, maintenant que c’est codé et vu que le temps presse, vous pouvez conserver cette approche, à condition de corriger les bugs.)

2019-06-22 07:52 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/utils/RandomRange.java
> +	public static HashMap<Double, Double> mapBound(int min, int max) {
Cette méthode est bien trop spécifique pour servir à quoi que ce soit d’autre qu’à être passée dans le constructeur d’une `DiscreteValueFunction`, donc il serait plus clair et pas moins général de directement renvoyer une `DiscreteValueFunction` (et donc de déplacer cette méthode dans la classe adéquate). Sinon, en lisant ce code, on se demande vraiment à quoi il sert.

2019-06-24 22:11 UTC, Amioplk commented on src/main/java/io/github/oliviercailloux/y2018/apartments/utils/RandomRange.java
> +	public static HashMap<Double, Double> mapBound(int min, int max) {
J'ai apporté une variante à l'approche pour que cela aie un intérêt.

2019-06-25 17:01 UTC, oliviercailloux approved these changes
FORMAT

Fusionnez après modifications mineures demandées.

2019-06-25 17:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/utils/RandomRange.java
> +		weightRange = weightRange.stream().map(d -> (d / sum) * s).collect(ImmutableList.toImmutableList());
Évitez de réutiliser une variable pour un autre objectif, cela introduit de gros risques de confusion (en lisant le début du code, on s’imagine facilement que `weightRange` sera toujours une `ArrayList`, et qu’il l’est toujours à la fin de la méthode).

2019-06-25 17:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/utils/RandomRange.java
> +	public static List<Double> weightRangeOfSum(double s, int size) {
Il est sympathique de renvoyer une `ImmutableList` pour offrir plus de garanties au client, lorsqu’il n’y a pas d’inconvénient (comme ici).

Nom obscur. `getRandomWeightsWithGivenSum` et nommer le premier paramètre `sum` par exemple serait nettement mieux.

2019-06-25 23:43 UTC, merged

2019-06-26 14:56 UTC, oliviercailloux commented
« Fusionnez après modifications mineures demandées. », pas « fusionner ».