MultiPartialValueFunction
Amioplk/Apartments pull request #33
Opened 2019-06-21 14:26 UTC by Amioplk

PieceWise a été remanié pour extends cette nouvelle classe.

2019-06-22 08:11 UTC, oliviercailloux requested changes
Expliquez-moi SVP pourquoi vous pensez avoir besoin d’une fonction qui renvoie des valeurs hors de l’intervalle [0, 1]. Cela ne devrait pas être nécessaire, grâce aux poids.

2019-06-22 08:11 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/MultiPartialValueFunction.java
> +public class MultiPartialValueFunction implements PartialValueFunction<Double> {
Ceci ne respecte pas le contrat de `PVF`, qui requiert des valeurs entre 0 et 1. `MPVF` ne peut donc pas étendre `PVF`.

2019-06-24 21:44 UTC, Amioplk commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/MultiPartialValueFunction.java
> +public class MultiPartialValueFunction implements PartialValueFunction<Double> {
Bonsoir,

Nous nous étions mal exprimés. L'utilité reste bien évidemment entre 0 et 1. La seule prétention de cette classe est d'accepter différents type de PVF par morceaux.

2019-06-24 22:07 UTC, oliviercailloux requested changes
FORMAT

2019-06-24 22:07 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/MultiPartialValueFunction.java
> + * A class which enables different types of PartialValueFunction
On ne comprend pas ce que sont ces types de PVF sans lire le code. Vous voulez dire, si je comprends bien, que « An object of this class represents a PartialValueFunction which is defined from multiple other PartialValueFunctions, each being active on a given range of the real line. For example, given the range [0, 10] with PartialValueFunction v1 and [10, 20] with v2, this function is the one that invokes v1 on the range [0, 10] and v2 on the range [10, 20].

2019-06-24 22:07 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/MultiPartialValueFunction.java
> +	public MultiPartialValueFunction(Map<Double, Double> parameters, SortedMap<Range<Double>, PartialValueFunction<Double>> partials) {
Je ne comprends pas l’intérêt de `parameters` (qui est de toute façon très mal nommé, lui donner un nom descriptif de ce qu’il représente serait sympathique) si on a `partials`, qui contient me semble-t-il toute l’info dont vous avez besoin.

2019-06-24 22:07 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/MultiPartialValueFunction.java
> +		LOGGER.info("The map of data has been successfully instantiated.");
Il faut aussi vérifier que la fonction est monotone non décroissante. Et que les range fournis sont contigus (Guava permet ceci facilement).

2019-06-24 22:07 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/MultiPartialValueFunction.java
> +	public void setPartials(SortedMap<Range<Double>, PartialValueFunction<Double>> partials) {
Non, l’objet doit être immuable.

2019-06-24 22:07 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/MultiPartialValueFunction.java
> +	protected SortedMap<Range<Double>, PartialValueFunction<Double>> partials;
`ImmutableSortedMap`

2019-06-24 22:12 UTC, oliviercailloux requested changes

2019-06-24 22:12 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/y2018/apartments/valuefunction/MultiPartialValueFunctionTest.java
> +		ConcurrentSkipListMap<Double, Double> map = new ConcurrentSkipListMap<>();
Mais pourquoi diable utiliser une `ConcurrentSkipListMap` ? En cherchant bien, on doit pouvoir trouver encore plus abscons. Utiliser plutôt le builder pour construire des `ImmutableSortedMap`.

2019-06-24 23:45 UTC, Amioplk commented
Bonjour,

Je suis d'accord avec toutes vos remarques excepté la plus importante en termes de changement d'implémentation : je ne pense pas que partials contienne toutes les informations nécessaires. Il manque l'utilité associée aux paliers. Cette information est justement portée par l'attribut map (qu'il faudrait renommer s'il reste).

La seule alternative que j'ai pu trouver est la suivante : changer le type de partials en ImmutableSortedMap<Range<Entry<Double,Double>>, PartialValueFunction<Double>>

mais il y a deux gros problèmes avec ce changement :
1. Cela devient complètement illisible
2. Le comparator sera incapable de comprendre lui même comment comparer deux ranges de Entrys (c'est déjà le cas actuellement en fait...)

Je voulais donc savoir si c'est une bonne idée ou si on peut trouver moins alambiqué et plus propre ?

2019-06-25 16:50 UTC, oliviercailloux requested changes
Bien d’accord que `ImmutableSortedMap<Range<Entry<Double,Double>>, PartialValueFunction>` est incompréhensible, d’ailleurs je ne comprends pas ce que ça représenterait, et ce n’est pas ce que j’avais en tête.

Je pense que je comprends toujours mal ce que vous voulez que `MultiPVF` puisse faire. Pouvez-vous m’expliquer mieux ? Êtes-vous d’accord avec la formulation du commentaire en Javadoc que j’ai proposé dans un commentaire précédent ? Si oui, pourquoi les fonctions et les range associées ne suffisent pas ? 

Pouvez-vous éventuellement décrire mathématiquement une `MultiPVF` ?

2019-06-25 23:42 UTC, Amioplk commented
La formulation de JavaDoc que vous avez formulé me convient totalement. Néanmoins, si on a v1 sur [0,1] et v2 sur [1,3], il faut savoir quelle est l'utilité associée au palier en 1. C'est justement l'information que prétend porter le deuxième attribut que vous trouvez inutile. Il nous faut une certaine continuité au niveau des paliers.
Mathématiquement, c'est assez délicat car on pourrait théoriquement alterner du continu sur [0,1] puis du discret sur [1,3].

Prenons un exemple, en supposant qu'on enlève le deuxième attribut. On prend une fonction linéaire sur [0,1] puis une autre fonction linéaire sur [1,3]. Si on garde l'implémentation avant cette tâche, LinearValueFunction calcule l'utilité de l'antécédent qu'on lui donne comme si l'utilité du minimum était toujours 0. Or ici, pour la deuxième fonction, le minimum est 1, et l'utilité attribuée est inconnue. On ne peut pas calculer l'utilité sans avoir cette information à un moment donné, à mon sens.

Je reformulerais comme cela pour ce qui est de l'exemple restreint aux LinearValueFunction : il faut deux points pour caractériser une droite. Or, LinearValueFunction prend par défaut le point (min,0) et (max,1) alors qu'il est possible que f(min)!=0 ou f(max)!=1

C'est pourquoi nous avons ajouté le constructeur prenant en paramètre deux Entry.

J'espère que c'est plus clair désormais.

2019-06-26 11:19 UTC, oliviercailloux commented
> La formulation de JavaDoc que vous avez formulé me convient totalement. Néanmoins, si on a v1 sur [0,1] et v2 sur [1,3], il faut savoir quelle est l'utilité associée au palier en 1. C'est justement l'information que prétend porter le deuxième attribut que vous trouvez inutile. Il nous faut une certaine continuité au niveau des paliers.
> Mathématiquement, c'est assez délicat car on pourrait théoriquement alterner du continu sur [0,1] puis du discret sur [1,3].
> 
> Prenons un exemple, en supposant qu'on enlève le deuxième attribut. On prend une fonction linéaire sur [0,1] puis une autre fonction linéaire sur [1,3]. Si on garde l'implémentation avant cette tâche, LinearValueFunction calcule l'utilité de l'antécédent qu'on lui donne comme si l'utilité du minimum était toujours 0.

Votre exemple me fait réaliser que ma proposition de Javadoc est au moins incomplète. 

Dans mon esprit initialement, la MPVF était simplement une union des PVF fournies, ce qui n’est pas votre compréhension il me semble, à la lecture de votre dernier commentaire. (Et de toute façon il faudrait le préciser dans la Javadoc, si mon idée initiale était celle que vous souhaitez adopter). 

Je m’explique, dans l’esprit de ma compréhension initiale. Une PVF a un co-domaine dans [0, 1] et, sauf erreur de ma part, d’après les conventions dans ce projet, est monotone non décroissante. Pour que la MPVF soit aussi non décroissante, il faut que v2 dans votre exemple ait comme co-domaine un sous-ensemble de [M, 1], où `M = max_{x ∈ domain(v1)}(v1(x)) = v1(1)`.

Il semble que vous ayez en tête un ré-échelonage des PVFs fournies. Mais il faut dans ce cas documenter comment vous comptez vous assurer que le résultat est bien dans [0, 1].

> Or ici, pour la deuxième fonction, le minimum est 1, et l'utilité attribuée est inconnue.

C’est là notre malentendu principal, je suppose. Pourquoi l’utilité attribuée à 1 est-elle inconnue ? C’est simplement v1(1).

2019-06-26 13:01 UTC, Amioplk commented
Effectivement je pense que c'est notre malentendu principal.

>Je m’explique, dans l’esprit de ma compréhension initiale. Une PVF a un co-domaine dans [0, 1] et, sauf erreur de ma part, d’après les conventions dans ce projet, est monotone non décroissante. Pour que la MPVF soit aussi non décroissante, il faut que v2 dans votre exemple ait comme co-domaine un sous-ensemble de [M, 1], où M = max_{x ∈ domain(v1)}(v1(x)) = v1(1).

Il se trouve qu'une PVF existe depuis le début du projet et permet de définir une LinearValueFunction décroissante. L'intérêt de MPVF c'est de pouvoir avoir un ré-echlonage pour pouvoir attribuer à n'importe quel PVF à n'importequel intervale. Concrètement, on pourrait à l'avenir vouloir traduire les deux comportements suivants :

1. Une fonction décroissante par morceaux car l'utilisateur ne veut par exemple pas être trop prêt des écoles pour ne pas être dérangé par le bruit
2. Une fonction non-monotone car l'utilisateur recherche un équilibre par exemple (il ne veut pas trop de salles de bain parce qu'il a peur que ses enfants se perdent par exemple -> c'est un exemple assez nul mais je pense qu'on peut trouver plus pertinent)

> Il semble que vous ayez au contraire en tête un ré-échelonage des PVFs fournies. Mais il faut dans ce cas documenter comment vous comptez vous assurer que le résultat est bien dans [0, 1].

C'est bien cela donc que nous voulions faire. Je peux donc ajouter dans la JavaDoc comment on compte assurer que le résultat est bien dans [0,1] mais c'est de la responsabilité de le PVF appelée de bien contrôler que l'utilité est entre 0 et 1 non ? C'est pour cela que j'ai ajouté des attributs minSubjectiveValue et maxSubjectiveValue dans LinearValueFunction et ReversedLinearValueFunction ainsi qu'un constructeur pour set ces valeurs. Or je me rend compte maintenant que je vais devoir faire cela pour toutes les classes qui implémentent PVF<Double> différentes... Les seules vérifications à effectuer pour moi ne concernent pas la monotonie mais plutôt le fait que les intervalles soient contigus et que le fonction soit continue.

Que dites-vous de remplacer dans ce cadre l'attribut map par un attribut List<Point2D> breakPoints qui donne le ré-echlonnage ? Il suffirait d'avoir des constructeurs dans les PVF qui acceptent deux paramètres Point2D et c'est bon.

2019-06-26 14:23 UTC, oliviercailloux commented
> Effectivement je pense que c'est notre malentendu principal.
> 
> > Je m’explique, dans l’esprit de ma compréhension initiale. Une PVF a un co-domaine dans [0, 1] et, sauf erreur de ma part, d’après les conventions dans ce projet, est monotone non décroissante. Pour que la MPVF soit aussi non décroissante, il faut que v2 dans votre exemple ait comme co-domaine un sous-ensemble de [M, 1], où M = max_{x ∈ domain(v1)}(v1(x)) = v1(1).
> 
> Il se trouve qu'une PVF existe depuis le début du projet et permet de définir une LinearValueFunction décroissante.

Ok, alors j’aurais dû écrire : Une PVF a un co-domaine dans [0, 1] et doit être monotone.

> L'intérêt de MPVF c'est de pouvoir avoir un ré-echlonage pour pouvoir attribuer à n'importe quel PVF à n'importequel intervale. Concrètement, on pourrait à l'avenir vouloir traduire les deux comportements suivants :
> 
>     1. Une fonction décroissante par morceaux pour l'utilité d'un utilisateur pour ce qui est du prix par nuit.
> 
>     2. Une fonction non-monotone car l'utilisateur recherche un équilibre par exemple (il ne veut pas trop de salles de bain parce qu'il a peur que ses enfants se perdent par exemple -> c'est un exemple assez nul mais je pense qu'on peut trouver plus pertinent)

Ok pour 1., mais pas pour 2.

La théorie de l’utilité multi-attribut suppose des fonctions monotones sur chaque attribut. Ce n’est pas très restrictif : dans votre exemple, l’utilisateur a en fait deux critères en tête (associés à deux PVFs monotones) : le temps passé à chercher ses enfants (à minimiser, monotone décroissant en fonction de l’augmentation du nombre de sdb) et le confort (à maximiser, monotone croissant).

> > Il semble que vous ayez au contraire en tête un ré-échelonage des PVFs fournies. Mais il faut dans ce cas documenter comment vous comptez vous assurer que le résultat est bien dans [0, 1].
> 
> C'est bien cela donc que nous voulions faire. Je peux donc ajouter dans la JavaDoc comment on compte assurer que le résultat est bien dans [0,1] mais c'est de la responsabilité de le PVF appelée de bien contrôler que l'utilité est entre 0 et 1 non ? C'est pour cela que j'ai ajouté des attributs minSubjectiveValue et maxSubjectiveValue dans LinearValueFunction et ReversedLinearValueFunction ainsi qu'un constructeur pour set ces valeurs. Or je me rend compte maintenant que je vais devoir faire cela pour toutes les classes qui implémentent PVF différentes... Les seules vérifications à effectuer pour moi ne concernent pas la monotonie mais plutôt le fait que les intervalles soient contigus et que le fonction soit continue.

- Oui, il faut ajouter dans la JavaDoc le détail de la combinaison des fonctions, et entre autres cela doit indiquer par conséquent comment on s’assure que le co-domaine de la MPVF est dans [0, 1], moyennant le fait que les PVFs fournies soient effectivement dans [0, 1].
- Oui, c’est la responsabilité des PVF fournies en paramètres d’avoir chacune un co-domaine dans [0, 1].
- Cette idée de LVF qui ne commence pas à 0 ou ne terminent pas à 1 (ou l’inverse pour une décroissante) complique tout et va à l’encontre de l’esprit de la théorie (qui incorpore ces différences d’échelles par le biais de différences de poids). Il faut conserver cette hypothèse ou me montrer pourquoi vous avez besoin de la relâcher et réfléchir à comment faire plus simple, si possible. Je ne vois pas pourquoi il faudrait la relâcher pour pouvoir créer une MPVF linéaire par morceaux, par exemple : moyennant un passage d’information sur les valeurs d’utilité extrêmes à votre MPVF, il n’est plus nécessaire de l’incorporer à la LVF elle-même, et cela ne la concerne pas.
- Par contre, j’ai maintenant compris pourquoi vous avez besoin des utilités des points extrêmes pour chaque PVF.

> Que dites-vous de remplacer dans ce cadre l'attribut map par un attribut List breakPoints qui donne le ré-echlonnage ? Il suffirait d'avoir des constructeurs dans les PVF qui acceptent deux paramètres Point2D et c'est bon.

Au risque de vous décevoir après toutes ces réflexions, je pense qu’il serait mieux de créer une classe PiecewiseLinearValueFunction pour implémenter ce que vous voulez faire directement. C’est moins général que votre idée, je vous l’accorde. Mais la généralité dans une classe n’est pas un bien en soi. Cela augmente la complexité, votre classe MPVF sera plus difficile à comprendre pour vos utilisateurs, plus difficile à manipuler car offrant moins de garantie (la linéarité, même par morceaux, ça a du bon et on a parfois envie de l’exploiter !), et en pratique, elle ne sera pas je pense plus générale, car je ne vois pas de raison de l’utiliser pour définir autre chose qu’une fonction linéaire par morceau, et je n’ai jamais vu ça dans la littérature technique.

Toutefois, si vous désirez absolument continuer dans cette voie, je ne vous l’interdit pas, et je vous laisse libre de choisir le type de paramètre. Notez aussi que vous devriez tenir compte de la possibilité que la fonction soit croissante ou décroissante (ou indiquer clairement vos hypothèses dans la doc). 

Mais j’insiste : une bonne conception requiert souvent d’avoir le courage d’effacer du code, ou de renoncer à une idée, après en avoir exploré les conséquences. (Concrètement, votre note ne sera bien sûr pas négativement impactée si vous renoncez à cette voie, car votre réflexion est bonne et les errements dans la conception sont parfois inévitables et font partie du travail de conception.)

2019-06-26 14:41 UTC, Amioplk commented
Très bien vous m'avez convaincu, même si je n'ai pas compris toutes les remarques je n'ai pas de background dans la théorie de l'utilité et peut-être que j'essaie de généraliser PieceWiseLinearValueFunction en vain ou même que c'est d'utilité 0 ^^

Je ferme donc cette PR.

Cordialement.

2019-06-26 14:41 UTC, closed without merging