enhanced generateRandom
Amioplk/Apartments pull request #34
Opened 2019-06-26 16:22 UTC by LaurenceTsizaza

Nous avons amélioré la fonction generateRandom pour s'assurer de générer des appartements réalistes.

2019-06-27 07:50 UTC, oliviercailloux requested changes
- En priorité, s’occuper des demandes en PR #29.
- Déplacer `generateRandom()` dans une classe `ApartmentGenerator` dans le package `apartment`. (Cela n’a rien à voir avec XML.)
- Transformer les deux méthodes statiques en méthodes d’instance

Il serait bon également de permettre de re-générer une même liste d’apartements de façon déterministe (utile pour reproduire un bug par exemple) (Facultatif). Pour ce faire :
- Inclure à la classe un champ `Random` contenant le générateur aléatoire
- Utiliser ce même générateur aléatoire partout dans le code

2019-06-29 12:40 UTC, oliviercailloux requested changes
Assurez-vous que le check Travis apparaisse SVP (cf. PR #29).

2019-06-30 15:00 UTC, oliviercailloux requested changes
Travis

2019-06-30 15:02 UTC, LaurenceTsizaza commented
@oliviercailloux 
Les erreurs de Travis correspondent à la classe Assert dans les tests. Elles seront résolues après le merge.

2019-06-30 18:00 UTC, oliviercailloux approved these changes

2019-06-30 18:02 UTC, merged