Deleted outdated Piecewise class
Amioplk/Apartments pull request #35
Opened 2019-06-26 16:29 UTC by LaurenceTsizaza

Nous avons supprimé l'ancienne classe PieceWiseLinearValueFunction suite à l'acceptation de la nouvelle classe. En effet, la nouvelle classe implémente PartialValueFunction, ce qui n'était pas le cas de l'ancienne.

2019-06-27 07:55 UTC, oliviercailloux requested changes
En priorité, s’occuper des demandes en PR #29.

2019-06-29 09:49 UTC, LaurenceTsizaza commented
Nous avons configuré Travis.

2019-06-29 12:31 UTC, oliviercailloux approved these changes

2019-06-29 12:32 UTC, merged

2019-06-29 12:32 UTC, oliviercailloux requested changes
Oups, j’ai peut-être été trop positif. Je ne vois pas les checks de Travis sur cette PR. Cf. PR #29.

2019-06-29 12:39 UTC, oliviercailloux commented
Bravo, vous êtes rapides à la détente. Ok pour la fusion de cette PR effectuée avant mon dernier commentaire. Résoudre la question Travis pour poursuivre (PR #29).