utilité indirecte
Amioplk/Apartments pull request #36
Opened 2019-06-26 21:50 UTC by Amioplk

Cette tâche permet à l'interface graphique en développement de récolter des réponses d'utilisateurs concernant leur utilité de manière indirecte (à leurs yeux).

Il sera possible de contrebalancer des poids si l'utilisateur déclare qu'un critère a plus d'importance qu'un autre. Il sera également possible de changer des limites quand l'utilisateur déclare avoir un minimum ou un maximum qu'il aimerait ne pas dépasser.

Nous avons essayé d'implémenter une certaine partie de l'utilité marginale. Le but était notamment de contre-balancer les poids lorsqu'un utilisateur déclarait pouvoir renoncer à X unités d'un critère pour un gain de Y unités d'un autre. Malheureusement, nous avons abandonné cette idée car, au delà du fait qu'il fallait traduire les dérivées partielles, les poids devaient à la fin avoir une somme égale à 1. Nous avons donc eu l'impression que la résolution de programmes linéaires (peut-être même avec des variables duales) serait inévitable. Aussi, comme nous manquons de temps, nous avons laissé tomber cette fonctionnalité.

2019-06-27 11:58 UTC, oliviercailloux requested changes
Dommage. Il aurait suffit de demander les compromis entre w1 et wi, où i est n’importe quel numéro de critère sauf le premier. Cela vous donne des taux de change de type w1 = 3 w2, w2 = 4 w3, etc. Ensuite, vous résolvez le système d’équation avec en plus la contrainte w1 + w2 + w3 = 1. Pas besoin d’un solveur particulier, vous pouvez le faire à la main. (Dans cet exemple, on obtient w1 + w2 + w3 = 1 donc w1 + 1/3 w1 + 1/12 w1 = 1 donc 12 w1 + 4 w1 + 1 w1 = 12 donc w1=12/17, et par conséquent w2 = 4/17 et w3 = 1/17.)

- En priorité, s’occuper des demandes en PR #29.
- n’écrivez pas systématiquement `this` quand ce n’est pas nécessaire, cela nuit à la lecture du code
- introduisez une PR juste pour le formatage comme requis par les instructions SVP (je sais que vous voulez gagner du temps, mais ceci aurait dû être fait depuis bien longtemps déjà et vous prendra qqs minutes)
- changez la logique : l’AVF ne doit pas changer. Ajouter une méthode dans `AVF`, `withPartialValueFunction(criterion: Criterion, valueFunction: PVF): AVF` qui renvoie une copie de l’AVF mais avec une fonction changée (pour celle en paramètre). Même chose pour `withWeights(weights: Map<Criterion, Double>): AVF`.

2019-06-27 11:58 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/AdaptiveWeightType.java
> +public enum AdaptiveWeightType {
Appeler ceci Criterion conviendrait mieux je pense.

2019-06-27 11:58 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/ApartmentValueFunction.java
> +	public void adaptBounds(String criteria, double newBound, boolean lower) {
Le premier paramètre devrait être `Criterion criterion` (singulier de criteria).

2019-06-28 13:04 UTC, Amioplk commented
Très bien pour les remarques, je ferme ce PR pour faire deux PRs différents pour le formatage et pour les fonctionnalités.

J'ai juste une question en ce qui concerne la résolution d'un système. Vous dites qu'on le fait à la main mais pour l'implémenter il faut passer par des matrices non ?

2019-06-28 13:04 UTC, closed without merging

2019-06-29 10:43 UTC, oliviercailloux commented
Pas dans ce cas-ci, vu la simplicité du système en question. Mon commentaire précédent avait pour but d’expliquer comment le résoudre sans utiliser de matrices.

Si vous ne comptez pas proposer un telle approche, merci de copier mon commentaire précédent dans la javadoc d’une classe associée en le marquant comme TODO (vous pouvez le laisser en français), pour que l’explication ne se perde pas.