Utility fonctionnality
Amioplk/Apartments pull request #39
Opened 2019-06-28 13:17 UTC by Amioplk

Suite du PR #36 sans le formatage de l'ancien code et avec les corrections de vos remarques @oliviercailloux .

2019-06-29 10:50 UTC, oliviercailloux requested changes
En priorité, s’occuper des demandes en PR #29.

2019-06-29 14:56 UTC, Amioplk commented
Travis nous pose des problèmes par rapport aux tests unitaires (il ne connait pas Assert).
Les modifications pour régler ce problème ont été faites dans la branche updateJunit (PR #41) mais changer sur toutes les branches est laborieux. Quoi qu'il en soit Travis est maintenant opérationnel. Pouvons-nous merge ?

2019-06-29 15:21 UTC, oliviercailloux commented
En effet, il est inutile de changer sur toutes les branches : dès que votre PR qui résoud les problèmes de compilation sera acceptée, on peut supposer que Travis passera sur les autres PRs également (à moins qu’il y ait d’autres problèmes ponctuels).

Il faut donc finaliser de toute urgence votre PR #41 (qui n’est toujours pas ok pour le moment, comme vous pouvez voir).

2019-06-29 15:26 UTC, oliviercailloux requested changes

2019-06-29 15:26 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/ApartmentValueFunction.java
> +	public ApartmentValueFunction adaptWeight(Criterion moreImportant, Criterion lessImportant) {
Ce nom est trompeur, il suggère qu’on modifie l’objet en place. `withAdaptedWeights` (par exemple) évite ce problème.

2019-06-29 15:57 UTC, Amioplk commented
Nous avons compilé avec mvn compile en local et cela nous donne le message Build Succes, ce qui veut certainement dire que c'est un problème de Travis.

2019-06-30 08:12 UTC, oliviercailloux requested changes
Chez moi mvn compile ne compile pas. (Il faut éventuellement lancer mvn clean avant pour être sûr qu’il re-compile.)

2019-06-30 08:16 UTC, oliviercailloux commented
Pardon, pour être plus précis, c’est `mvn test` (sur la branche `utilityFonctionnality`) qui ne passe pas (le problème étant dans les tests, on pouvait s’y attendre).

2019-06-30 15:27 UTC, closed without merging