Gui utility
Amioplk/Apartments pull request #40
Opened 2019-06-28 16:50 UTC by SandraSalame

Pour cette itération, on a créé la classe AskOpinionForUtility pour notre démonstration.

En effet c'est un GUI qui vas poser deux types de questions à l'utilisateur pour l'aider à déterminer son utilité. Le premier type de question lui demande de donner une valeur minimum de surface et de nombre de chambres pour accepter un appartement. Le deuxième type de question lui demande de choisir entre deux éléments lequel il considère le plus important.
Ensuite on récupère ces données et on adapte son utilité avec les fonctions de ApartementValueFunction (d'ou le fait de créer une branche à partir de utility de l'autre binôme en attendant les corrections; on ne pouvait pas s'attendre ).
Puis à la fin on affiche la liste d'appartement triée selon les critères de l'utilisateur(cela nous permet de faire des tests). 
Pour la démonstration on fera un main.

Difficultés rencontrées: Récupérer les données saisies par l'utilisateur pour le premier type de question et récupérer les deux valeurs meme l'autre choix qui n'a pas été sélectionné pour le deuxième type de question .
Aussi adapter la fonction adaptWeight de ApartementValueFunction à cause de ses paramètres.

2019-06-29 11:02 UTC, oliviercailloux requested changes
- En priorité, s’occuper des demandes en PR #29.
- Références de méthodes systématiques SVP

2019-06-29 11:02 UTC, oliviercailloux commented on pom.xml
> +
Corriger ce POM.

2019-06-29 11:02 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/AskOpinionForUtility.java
> +	ArrayList<String> attributsPasImportant;
Privilégier les types plus généraux quand cela n’a pas d’inconvénient.

2019-06-29 11:02 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/AskOpinionForUtility.java
> +	 * This array will stock the user's answers (when he presses the button)
C’est une liste, pas un array (en Java, désigne un tableau primitif, pas un objet). Mais de toute façon, inutile de répéter le type dans la doc, on le voit bien. “Keeps the user’s answers (when he presses the button)” suffirait.

2019-06-29 11:02 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/AskOpinionForUtility.java
> +		finish.addListener(SWT.Selection, new Listener() {
Utiliser une référence de méthode pour éviter l’imbrication

2019-06-29 11:02 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/AskOpinionForUtility.java
> +				 * System.out.print("Les attribut important sont : "); for (int j = 0; j <
BP style ; utilisez un logger, cela sert à ça.

2019-06-29 11:02 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/Layout2.java
> +public class Layout2 {
Un nom un peu plus descriptif du rôle de cette classe serait une aide bienvenue pour le lecteur de votre code (et pour aider à la réflexion sur la conception du logiciel).

2019-06-29 11:14 UTC, Aichaaa commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/Layout2.java
> +public class Layout2 {
Oui, en fait c'est juste une classe qu'on a crée pour remplacer LayoutApartment (qui affiche la liste d'appartement) en attendant que le PR cette dernière soit acceptée. Normalement elle sera supprimée quand on va tout merge.

2019-06-30 08:03 UTC, oliviercailloux requested changes
Cf. commentaires précédents :
- Corriger le POM
- Privilégier les types plus généraux quand cela n’a pas d’inconvénient
Etc. (prendre tous les commentaires en compte ou m’expliquer pourquoi ils ne le sont pas)

2019-06-30 14:51 UTC, Amioplk commented
Bonjour, 

Nous nous permettons de nous ajouter moi (Amioplk) et Alexis (alexisperdereau) sur cette PR car la PR #39 pose beaucoup de problèmes de compatibilité avec Master.

Etant donné que cette branche GuiUtility a été crée sur notre ancienne branche utility, ces deux tâches sont intimmement liées et des corrections pour la fonctionnalité d'adaptation devront également être faites du côté du GUI pour que le fonctionnement reste bon.

Sion concernant vos anciennes remarques, nous avons répondu à toutes vos attentes sauf une seule : nous n'arrivons pas à utiliser une référence de méthodes (avec lambda expression type AskOpinionForUtility::onClickFinish) dans ce cadre précis avec les listeners. Nous espérons que vous ne nous en tiendrez pas rigueur.

Coriadlement.

2019-06-30 14:56 UTC, oliviercailloux approved these changes
Toujours pas de références de méthodes, mais on peut s’en passer, vu l’urgence de la situation.
Ok pour fusion, moyennant corrections mineures.

2019-06-30 14:56 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/AskOpinionForUtility.java
> +												 */
BP style

2019-06-30 14:56 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/AskOpinionForUtility.java
> +	List<String> attributsPasImportant;
In English please

2019-06-30 15:26 UTC, merged