Migrate Junit4 to Junit5
Amioplk/Apartments pull request #41
Opened 2019-06-28 22:23 UTC by zeinaalwazzan

Pour ce pull request, nous avons mis à jour les tests unitaires avec Junit5. Pour cela, nous avons ajouté dans le pom les dépendances nécessaire au déroulement du Junit5 et nous avons modifié les imports dans les tests ainsi que les asserts pour que les tests fonctionnent avec Junit5.
Le test ValueDistFunction ne fonctionne pas puisqu'il n'y a pas un fichier comportant une clé "API_KEY.txt" pour accéder à l'api Google Maps.

2019-06-29 12:24 UTC, oliviercailloux requested changes
- Initialiser Travis comme demandé en PR #29 est requis avant acceptation d’autres modifications
- Enlever l’annotation @Test sur le test qui ne passe pas en ajoutant un commentaire en Javadoc expliquant pourquoi ce test est désactivé.

2019-06-29 12:24 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/y2018/apartments/piecewise/PiecewiseTest.java
> +//import org.junit.Assert;
BP style

2019-06-29 15:12 UTC, LaurenceTsizaza commented
Les modifications de cette branche vont résoudre les conflits dans les autres branches.

2019-06-29 16:22 UTC, oliviercailloux requested changes
Comme vous pouvez le constater, il y a toujours un problème.

2019-06-29 16:37 UTC, LaurenceTsizaza commented
@oliviercailloux 
Travis détecte une exception de pointeur nul dans un test:
--
[ERROR] Errors: 
[ERROR]   ToXmlPropertiesTest.readApartmentTest:44 » NullPointer
[INFO] 
[ERROR] Tests run: 25, Failures: 0, Errors: 1, Skipped: 0
--
--
ligne 44: Apartment a1 = r.readApartment(f1);
--
Cependant, lorsqu'on run ce test en local, il n'y a aucune erreur, ni a1, ni f1 (InputStream) n'est nul. On ne voit pas comment résoudre le conflit.

2019-06-30 08:30 UTC, oliviercailloux requested changes
Lorsque je repasse au commit 2777faa et exécute `mvn test`, il échoue également.

La clé du mystère est très probablement que vous aviez une ancienne version de votre fichier `xmlfileTest.xml` encore présent dans un répertoire où il n’est maintenant plus.

Restaurez l’annotation `@Test` et résolvez le problème, cela devrait être facile à partir du moment où vous arrivez à le reproduire en local.

2019-06-30 10:18 UTC, LaurenceTsizaza commented
Bonjour @oliviercailloux ,
Nous avons ajouté le fichier xmlfileTest.xml dans le repository src\test\resources\io\github\oliviercailloux\y2018\apartments\toxmlproperties. Désomais mvn test n'échoue plus. Cependant, Travis échoue encore.

2019-06-30 11:11 UTC, oliviercailloux commented
`mvn test` (et Eclipse) échouent toujours sur la branche `updateJunit` sur mon ordinateur. Et pour la même raison : le fichier en question n’est pas dans la branche en question à l’endroit attendu par le code.

2019-06-30 11:14 UTC, oliviercailloux commented
C’est une erreur d’inattention. Voyez quel est le nom complet de la ressource que votre test essaie de charger. Faites attention à la casse.

2019-06-30 14:07 UTC, oliviercailloux approved these changes
Ok pour fusion après correction de la version de Surefire-plugin.

2019-06-30 14:07 UTC, oliviercailloux commented on pom.xml
> +			    <version>3.0.0-M3</version>
Évitez l’usage de versions en développement, cela attire des ennuis. Restez à la dernière version non suffixée "bizarrement".

2019-06-30 14:07 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/y2018/apartments/toxmlproperties/ToXmlPropertiesTest.java
> +				"src/test/resources/io/github/oliviercailloux/y2018/apartments/readapartments/xmlfileTest.xml");
BP resources, mais passons car le temps presse.

2019-06-30 14:19 UTC, merged