Update functionalities
Amioplk/Apartments pull request #6
Opened 2019-05-23 11:14 UTC by LaurenceTsizaza

Functions updated : 
- Apartment.ToString() => added StringHelper
- ModifyApartmentGUI.java => added thrown exceptions
- ReadApartmentXMLFormat.jave => used reflection

2019-05-23 19:23 UTC, oliviercailloux requested changes
DER (out.log)

2019-05-23 19:23 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/apartment/Apartment.java
> +	// public String toString() {
Enlever ces commentaires.

2019-05-23 19:23 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/apartment/Apartment.java
>  	 */
La javadoc doit accompagner la méthode qu’elle commente. Mais en l’occurrence, ces commentaires me semblent inutiles.

2019-05-23 19:23 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/apartment/Apartment.java
> +		ToStringHelper titleTS = MoreObjects.toStringHelper(this);
Ce n’est pas comme ça que le StringHelper s’utilise. Lire la Javadoc.

2019-05-23 19:23 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/ModifyApartmentGUI.java
> +	static public void main(String args[]) throws IOException, IllegalArgumentException, IllegalAccessException {
Inutilement détaillé. Toutes les méthodes peuvent lancer `IllegalArgumentException`, ce n’est aucunement remarquable. Concernant `IllegalAccessException`, si vous pensez qu’il est intéressant de le signaler, il faut documenter les conditions dans lesquelles il est lancé, sinon ça n’aide pas beaucoup. (À moins que ce soit évident.)
Dans tous les cas, ce niveau de détail n’est pas utile sur une méthode `main`, qui n’est pas faite pour être invoquée par un programmeur.

2019-05-23 19:23 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/readapartments/ReadApartmentsXMLFormat.java
> +    	for(Field f : fields) {
Je ne pense pas que ceci soit une amélioration. Si on renomme un champ dans `Apartment`, ce code échouera au runtime. Il vaut mieux garder une liaison explicite ici.

2019-05-28 11:13 UTC, Amioplk commented
@oliviercailloux no DER : asking for review

2019-05-29 08:18 UTC, oliviercailloux requested changes
FORMAT

2019-05-29 08:18 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/apartment/Apartment.java
> +		apart.add(this.address, true);
Avez-vous compris ce que fait cette méthode ? Avez-vous testé ce code ?

2019-05-29 08:18 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/ModifyApartmentGUI.java
> +		}
La version précédente me semble mieux : code plus concis, exception plus visible pour le programmeur car annoncée sur l’en-tête de la méthode, et l’exception apparaitra plus clairement à l’utilisateur.

2019-05-29 08:18 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/ModifyApartmentGUI.java
> +	 * @throws IOException if an exception occurs in getApartment()
Je ne trouve pas ce commentaire utile pour l’utilisateur de la classe, et il est fragile car sujet à changement dès que la structure du code changera.

2019-05-29 08:18 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/ModifyApartmentGUI.java
> +		}
EXC

2019-05-29 08:18 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/readapartments/ReadApartmentsXMLFormat.java
>  			LOGGER.error("Impossible to create an apartment if a floor Area, a title or an address is missing.");
Éviter de logger en plus de lancer une exception : celui qui récupère l’exception risque de faire de même, menant à des logs répétés.

2019-05-29 08:18 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/y2018/apartments/readApartments/ReadApartmentsXMLFormatTest.java
> +	void readApartmentTest() throws IOException, IllegalArgumentException, IllegalAccessException{
Inutile d’annoncer les exceptions de façon aussi détaillées. `IllegalArgumentException`, de plus, est curieux ici, puisqu’il n’y a pas d’arguments.

2019-06-04 10:45 UTC, oliviercailloux requested changes
DER. Utiliser gitignore.
ECL.
Je termine la review après correction.

2019-06-04 10:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/apartment/Apartment.java
> +		apart.add("FloorArea", Double.toString(this.floorArea));
Pourquoi `Double.toString` ?

2019-06-04 10:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/ModifyApartmentGUI.java
> +	 * @throws IOException if an exception occurs in getApartment()
Ce n’est pas vrai, certaines exceptions qui peuvent se produire ne sont pas de ce type, et le commentaire n’est toujours pas très utile. Retirez simplement la partie @throws

2019-06-04 10:45 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/gui/ModifyApartmentGUI.java
> +	private void initializeField() throws IOException, IllegalAccessException {
Il n’est pas utile d’annoncer les exceptions de type `IllegalAccessException`, ces problèmes ne surviennent que dans des environnements inhabituels.

2019-06-17 15:43 UTC, oliviercailloux requested changes
FORMAT
(Je continue la review ensuite)

2019-06-17 15:43 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/y2018/apartments/apartment/Apartment.java
> +		//return apart.toString().equals(this.toString()); -> not exhaustive
BP style comments

2019-06-17 15:43 UTC, oliviercailloux requested changes
FORMAT
(Je continue la review ensuite)

2019-06-17 15:49 UTC, oliviercailloux requested changes
FORMAT
(Je continue la review ensuite)

2019-06-17 15:50 UTC, oliviercailloux commented
Oups, désolé pour le duplicat, problème réseau GitHub

2019-06-19 16:00 UTC, oliviercailloux requested changes
conflits

2019-06-20 14:21 UTC, oliviercailloux requested changes
FOCUS. Introduire une PR qui ne fait que le re-formatage pour distinguer des vrais changements.

2019-06-29 14:51 UTC, closed without merging